# Toddler Project - Reflection
## Part 1: File Structure

Below is the file structure for my project:

[File Structure](documents/file%20structure.docx)

## Part 2: GitHub Repository Link

You can view my project on GitHub:  
[GitHub Repository](https://github.com/Oby-Ok/baby-project-Movies/tree/toddler_project)

## Creating fake data

In [2]:
import pandas as pd

## Loading the Dataframes - Superhero and Publisher

In [3]:
## Copied dataframes from Amy's file:


superheroes = pd.DataFrame({
    "name": ["Magneto", "Storm", "Mystique", "Batman", "Joker", "Catwoman", "Hellboy"],
    "alignment": ["bad", "good", "bad", "good", "bad", "bad", "good"],
    "gender": ["male", "female", "female", "male", "male", "female", "male"],
    "publisher": ["Marvel", "Marvel", "Marvel", "DC", "DC", "DC", "Dark Horse Comics"]
})

publishers = pd.DataFrame({
    "publisher": ["DC", "Marvel", "Image"],
    "year_founded": [1934, 1939, 1992]
})

In [8]:
import pandas as pd
import numpy as np

# Define the structure of the new fake dataset
fake_data = pd.DataFrame({
    "expected_salary": np.random.choice([2000, 2500, 3000, 3500, 4000, 5000], size=50),
    "gender": np.random.choice(["Male", "Female"], size=50),
    "age": np.random.randint(18, 40, size=50),
    "transport_mode": np.random.choice(["Walk", "Drive", "Public Transit"], size=50),
    "monthly_expenses": np.random.randint(500, 5000, size=50)
})

# Save as CSV
fake_data.to_csv("../data/fake_data.csv", index=False)
print("✅ Fake data generated and saved as 'fake_data.csv'.")

✅ Fake data generated and saved as 'fake_data.csv'.

In [4]:
## inspect everything.
## By doing this in its own cell, I'm not constantly overwriting my df while experimenting

print(superheroes)

publishers

       name alignment  gender          publisher
0   Magneto       bad    male             Marvel
1     Storm      good  female             Marvel
2  Mystique       bad  female             Marvel
3    Batman      good    male                 DC
4     Joker       bad    male                 DC
5  Catwoman       bad  female                 DC
6   Hellboy      good    male  Dark Horse Comics

  publisher  year_founded
0        DC          1934
1    Marvel          1939
2     Image          1992

# Merging Superheroes & Publishers Data
## We introduced inconsistencies in the dataset by:

Changing Magneto’s alignment from "bad" to "good".
Adding a second entry for Marvel with a conflicting founding year (1939 & 1961).

## Joins/Merging  the fake data

In [5]:
# Modified Superheroes DataFrame with an inconsistency (Magneto's alignment changed)
superheroes = pd.DataFrame({
    "name": ["Magneto", "Storm", "Mystique", "Batman", "Joker", "Catwoman", "Hellboy", "Iron Man"],
    "alignment": ["good", "good", "bad", "good", "bad", "bad", "good", "bad"],  # Changed Magneto to "good"
    "gender": ["male", "female", "female", "male", "male", "female", "male", "male"],
    "publisher": ["Marvel", "Marvel", "Marvel", "DC", "DC", "DC", "Dark Horse Comics", "Marvel"]
})

# Modified Publishers DataFrame with a conflicting founding year for Marvel
publishers = pd.DataFrame({
    "publisher": ["DC", "Marvel", "Marvel", "Image"],
    "year_founded": [1934, 1939, 1961, 1992]  # Added conflicting second year for Marvel
})

## Merge Strategy:¶
We performed a many-to-one merge using:

merged_superheroes = pd.merge(superheroes, publishers, on ="publisher", how ="inner")

This keeps only matching publishers, dropping any superheroes whose publisher isn't listed. Since Marvel appears twice in the publishers dataset, superheroes from Marvel are duplicated in the merge.

In [6]:
# Merge the datasets
merged_superheroes = pd.merge(superheroes, publishers, on="publisher", how="inner")

# Show merged dataset
from IPython.display import display

In [7]:
# Show the merged dataframe
display(merged_superheroes)

        name alignment  gender publisher  year_founded
0    Magneto      good    male    Marvel          1939
1    Magneto      good    male    Marvel          1961
2      Storm      good  female    Marvel          1939
3      Storm      good  female    Marvel          1961
4   Mystique       bad  female    Marvel          1939
5   Mystique       bad  female    Marvel          1961
6     Batman      good    male        DC          1934
7      Joker       bad    male        DC          1934
8   Catwoman       bad  female        DC          1934
9   Iron Man       bad    male    Marvel          1939
10  Iron Man       bad    male    Marvel          1961

In [8]:
import pandas as pd
from IPython.display import display  # For better table formatting 
# Superheroes DataFrame
superheroes = pd.DataFrame({
    "name": ["Magneto", "Storm", "Mystique", "Batman", "Joker", "Catwoman", "Hellboy"],
    "alignment": ["bad", "good", "bad", "good", "bad", "bad", "good"],
    "gender": ["male", "female", "female", "male", "male", "female", "male"],
    "publisher": ["Marvel", "Marvel", "Marvel", "DC", "DC", "DC", "Dark Horse Comics"]
})

# Publishers DataFrame
publishers = pd.DataFrame({
    "publisher": ["DC", "Marvel", "Image"],
    "year_founded": [1934, 1939, 1992]
})

## Different Merge Types
We test different types of merges:

Inner Join: Keeps only matching publishers.
Left Join: Keeps all superheroes, adding publisher info where available.
Right Join: Keeps all publishers, adding superheroes where available.
Outer Join: Keeps all superheroes and publishers, filling missing values with NaN.

In [9]:
# 1 Different Merge Types
inner_merge = pd.merge(superheroes, publishers, on="publisher", how="inner")
left_merge = pd.merge(superheroes, publishers, on="publisher", how="left")
right_merge = pd.merge(superheroes, publishers, on="publisher", how="right")
outer_merge = pd.merge(superheroes, publishers, on="publisher", how="outer")

## Using Indicator to Track Merge Source¶
This merge adds a _merge column showing whether a row is from:

"both" → Found in both datasets.
"left_only" → Found only in the superheroes dataset.
"right_only" → Found only in the publishers dataset.

In [10]:
# 2 Using Indicator to Track Merge Source
merge_with_indicator = pd.merge(superheroes, publishers, on="publisher", how="outer", indicator=True)

# 2 Using Indicator to Track Merge Source
merge_with_indicator = pd.merge(superheroes, publishers, on="publisher", how="outer", indicator=True)

In [11]:
# 3 Handling Duplicate Column Names with Suffixes
merge_with_suffixes = pd.merge(superheroes, publishers, on="publisher", suffixes=("_hero", "_pub"))

## Sorting After Merge
We sort the merged result by the publisher column to organize the output.

In [12]:
# 4 Sorting After Merge
sorted_merge = pd.merge(superheroes, publishers, on="publisher", how="left", sort=True)

## Using left_on= and right_on= (Merging on Different Column Names)¶
Sometimes, column names don’t match between DataFrames.
Here, we rename "publisher" in the publishers DataFrame to "company" and merge.

In [13]:
# 5 Using Left and Right On (Different Column Names)
publishers_renamed = publishers.rename(columns={"publisher": "company"})
merge_with_diff_names = pd.merge(superheroes, publishers_renamed, left_on="publisher", right_on="company")

## Merging Based on Index
Instead of merging on a column, we merge using the index (name in superheroes and publisher in publishers). Using left_on= and right_on= (Merging on Different Column Names)** Sometimes, column names don’t match between DataFrames.
Here, we rename "publisher" in the publishers DataFrame to "company" and merge.

In [14]:
# 6 Merging Based on Index
merge_on_index = pd.merge(superheroes.set_index("name"), publishers.set_index("publisher"), left_index=True, right_index=True, how="inner")

## Validate Merge (One-to-One)
We check if the merge follows a one-to-one relationship.

If the same publisher appears multiple times in the left DataFrame, validate="one_to_one" raises an error.
The error message

In [15]:
# 7 Validate Merge (One-to-One)
try:
    validated_merge = pd.merge(superheroes, publishers, on="publisher", how="left", validate="one_to_one")
except Exception as e:
    validated_merge = str(e)  # Capture validation error message

# 2. Displaying the Results

In [17]:
#  Display Results in Jupyter Notebook
display(inner_merge.head())  # Show first few rows
display(left_merge.head())
display(right_merge.head())
display(outer_merge.head())
display(merge_with_indicator.head())
display(merge_with_suffixes.head())
display(sorted_merge.head())
display(merge_with_diff_names.head())
display(merge_on_index.head())

# Print validation error (if any)
print("Validation Error (if any):", validated_merge)

       name alignment  gender publisher  year_founded
0   Magneto       bad    male    Marvel          1939
1     Storm      good  female    Marvel          1939
2  Mystique       bad  female    Marvel          1939
3    Batman      good    male        DC          1934
4     Joker       bad    male        DC          1934

       name alignment  gender publisher  year_founded
0   Magneto       bad    male    Marvel        1939.0
1     Storm      good  female    Marvel        1939.0
2  Mystique       bad  female    Marvel        1939.0
3    Batman      good    male        DC        1934.0
4     Joker       bad    male        DC        1934.0

       name alignment  gender publisher  year_founded
0    Batman      good    male        DC          1934
1     Joker       bad    male        DC          1934
2  Catwoman       bad  female        DC          1934
3   Magneto       bad    male    Marvel          1939
4     Storm      good  female    Marvel          1939

       name alignment  gender          publisher  year_founded
0    Batman      good    male                 DC        1934.0
1     Joker       bad    male                 DC        1934.0
2  Catwoman       bad  female                 DC        1934.0
3   Hellboy      good    male  Dark Horse Comics           NaN
4       NaN       NaN     NaN              Image        1992.0

       name alignment  gender          publisher  year_founded      _merge
0    Batman      good    male                 DC        1934.0        both
1     Joker       bad    male                 DC        1934.0        both
2  Catwoman       bad  female                 DC        1934.0        both
3   Hellboy      good    male  Dark Horse Comics           NaN   left_only
4       NaN       NaN     NaN              Image        1992.0  right_only

       name alignment  gender publisher  year_founded
0   Magneto       bad    male    Marvel          1939
1     Storm      good  female    Marvel          1939
2  Mystique       bad  female    Marvel          1939
3    Batman      good    male        DC          1934
4     Joker       bad    male        DC          1934

       name alignment  gender          publisher  year_founded
0    Batman      good    male                 DC        1934.0
1     Joker       bad    male                 DC        1934.0
2  Catwoman       bad  female                 DC        1934.0
3   Hellboy      good    male  Dark Horse Comics           NaN
4   Magneto       bad    male             Marvel        1939.0

       name alignment  gender publisher company  year_founded
0   Magneto       bad    male    Marvel  Marvel          1939
1     Storm      good  female    Marvel  Marvel          1939
2  Mystique       bad  female    Marvel  Marvel          1939
3    Batman      good    male        DC      DC          1934
4     Joker       bad    male        DC      DC          1934

Empty DataFrame
Columns: [alignment, gender, publisher, year_founded]
Index: []

Validation Error (if any): Merge keys are not unique in left dataset; not a one-to-one merge

# **3. Handling a Compound Key in `pd.merge()`**
A **compound key** is a combination of **two or more columns** used to merge datasets.  
For example, if we have **Iron Man** in both **Comics** and **Movies**, merging only on `"name"` would cause incorrect matches.

---

### Why Use a Compound Key?
 Prevents **wrong merges** when a single column isn't unique.  
 Useful when the same entity appears in **different categories** (e.g., Movies vs. Comics).  
 Helps **differentiate versions of the same entity**.

---

###  Example: Merging Superheroes with Medium (Comics, Movies, TV)
We merge on **both** `"name"` and `"medium"` (Movie/TV/Comic).

In [18]:
import pandas as pd
from IPython.display import display  # For Jupyter formatting

# Superheroes dataset with an added "medium" column
superheroes = pd.DataFrame({
    "name": ["Iron Man", "Iron Man", "Batman", "Superman"],
    "medium": ["Comics", "Movies", "Comics", "TV"],
    "publisher": ["Marvel", "Marvel", "DC", "DC"]
})

# Publishers dataset with additional details
publishers = pd.DataFrame({
    "publisher": ["Marvel", "Marvel", "DC", "DC"],
    "medium": ["Comics", "Movies", "Comics", "TV"],
    "year_founded": [1939, 2008, 1934, 1952]
})

# Merge on both "publisher" and "medium" to differentiate versions
merged_compound_key = pd.merge(superheroes, publishers, on=["publisher", "medium"], how="inner")

# Display merged data
display(merged_compound_key)

       name  medium publisher  year_founded
0  Iron Man  Comics    Marvel          1939
1  Iron Man  Movies    Marvel          2008
2    Batman  Comics        DC          1934
3  Superman      TV        DC          1952

# **4. Difference Between `join()` and `merge()`**
`pd.merge()` and `df.join()` both combine DataFrames, but they work differently.

- **`pd.merge()`** is more flexible and allows merging on **specific columns**.
- **`df.join()`** is used for merging based on **index**.
*merge() allows more flexibility with join types and keys.
*join() is faster for merging large datasets on an index.

### **When to Use What?**
**Use `pd.merge()`** when merging **two DataFrames on a specific column**.  
**Use `df.join()`** when merging **on index instead of column names**.


---

# **5. What Should Be the Default Merge Type?**
By default, `pd.merge()` uses `"inner"`, meaning:
- Only **matching rows** from both DataFrames are kept.
- Non-matching rows are **dropped**.

### **Best Merge Type?**
 `"inner"` is useful but may lose important data.  
 `"left"` keeps all records from the main dataset.  
 `"outer"` keeps everything, filling missing values.  
 `"right"` is like `"left"`, but prioritizes the second dataset.  
 `"anti"` (not in `pd.merge()`, but available in SQL) removes matching rows.

**For most cases, `"left"` is the best choice to retain all important data.**

# **References**
The concepts and code used in this notebook are based on standard documentation and resources related to Pandas and data merging techniques. The following references were used:

 **Real Python Tutorials**  
   - "How to Combine DataFrames with Pandas": [https://realpython.com/pandas-merge-join-concat/](https://realpython.com/pandas-merge-join-concat/)  
 

**ChatGPT (OpenAI, 2024)**  
   - Some explanations and structuring of markdown and Python examples were generated using **ChatGPT**. The AI-assisted responses were used to clarify `pd.merge()`, `df.join()`, and best practices for merging DataFrames.